# Generated by Django 3.1.7 on 2021-04-09 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='local',
            old_name='week',
            new_name='day',
        ),
    ]
