# Generated by Django 3.1.7 on 2021-04-11 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210409_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='local',
            old_name='day',
            new_name='week',
        ),
    ]
