# Generated by Django 3.1.7 on 2021-04-11 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210411_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='local',
            old_name='week',
            new_name='day',
        ),
    ]
