# Generated by Django 3.1.7 on 2021-04-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210411_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='detection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('lat', models.CharField(max_length=10)),
                ('lot', models.CharField(max_length=10)),
            ],
        ),
    ]
