# Generated by Django 3.1.7 on 2021-04-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_detection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='lat',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='detection',
            name='lot',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='detection',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
